"""add_admin_menu_tables

Revision ID: 78b97beda8f8
Revises: 1a7ed6cbedf6
Create Date: 2026-08-02 02:05:38.292526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b97beda8f8'
down_revision: Union[str, Sequence[str], None] = '1a7ed6cbedf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_menu',
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('menu_type', sa.String(length=16), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_menu_parent_id'), 'admin_menu', ['parent_id'], unique=False)
    op.create_table('admin_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['admin_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_menu')
    op.drop_index(op.f('ix_admin_menu_parent_id'), table_name='admin_menu')
    op.drop_table('admin_menu')
    # ### end Alembic commands ###
