"""add admin_user_role

Revision ID: 159b037bab27
Revises: b2f14b3e3fb3
Create Date: 2026-07-31 16:56:08.198068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159b037bab27'
down_revision: Union[str, Sequence[str], None] = 'b2f14b3e3fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('role', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_admin_user_role'), 'admin_user', ['role'], unique=False)
    # 将所有管理员账号的角色设置为超级管理员
    op.execute("UPDATE admin_user SET role = 'super_admin' WHERE is_deleted = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_role'), table_name='admin_user')
    op.drop_column('admin_user', 'role')
    # ### end Alembic commands ###
