"""add admin_menu_api_2 remark

Revision ID: ee3aad681a1d
Revises: 0b4232a3bebb
Create Date: 2026-08-03 21:10:43.815220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee3aad681a1d'
down_revision: Union[str, Sequence[str], None] = '0b4232a3bebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu_api', sa.Column('remark', sa.String(length=255), nullable=True))
    op.drop_column('admin_role_menu', 'remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_menu', sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('admin_menu_api', 'remark')
    # ### end Alembic commands ###
