"""add_admin_rbac_tables

Revision ID: 9b0042cc36c2
Revises: 159b037bab27
Create Date: 2026-08-01 00:26:11.183939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0042cc36c2'
down_revision: Union[str, Sequence[str], None] = '159b037bab27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permission',
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permission_code'), 'admin_permission', ['code'], unique=True)
    op.create_table('admin_role',
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_role_code'), 'admin_role', ['code'], unique=True)
    op.create_table('admin_role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_permission')
    op.drop_index(op.f('ix_admin_role_code'), table_name='admin_role')
    op.drop_table('admin_role')
    op.drop_index(op.f('ix_admin_permission_code'), table_name='admin_permission')
    op.drop_table('admin_permission')
    # ### end Alembic commands ###
