"""add admin_menu_api remark

Revision ID: 0b4232a3bebb
Revises: 3aaf08d5dccd
Create Date: 2026-08-03 21:08:57.061770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4232a3bebb'
down_revision: Union[str, Sequence[str], None] = '3aaf08d5dccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_menu', sa.Column('remark', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_menu', 'remark')
    # ### end Alembic commands ###
