"""add admin_user

Revision ID: ec49755d4036
Revises: c119b9924624
Create Date: 2026-07-29 23:55:45.848358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec49755d4036'
down_revision: Union[str, Sequence[str], None] = 'c119b9924624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=18), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_phone_number'), 'admin_user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_phone_number'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
