"""drop_admin_menu_permission_code

Revision ID: 67d884b5d853
Revises: 0ba098c09c8c
Create Date: 2026-08-03 17:11:49.111385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67d884b5d853'
down_revision: Union[str, Sequence[str], None] = '0ba098c09c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_menu', 'permission_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('permission_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    # ### end Alembic commands ###
