"""drop_admin_permission_tables

Revision ID: 3aaf08d5dccd
Revises: 67d884b5d853
Create Date: 2026-08-03 17:23:06.478117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3aaf08d5dccd'
down_revision: Union[str, Sequence[str], None] = '67d884b5d853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # MySQL DDL 无事务：上次可能已删掉关联表，需 IF EXISTS
    op.execute("DROP TABLE IF EXISTS admin_role_permission")
    op.execute("DROP TABLE IF EXISTS admin_permission")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permission',
    sa.Column('is_deleted', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('update_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('group_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )   
    op.create_table('admin_role_permission',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permission.id'], name=op.f('admin_role_permission_ibfk_1')),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], name=op.f('admin_role_permission_ibfk_2')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    op.create_index(op.f('ix_admin_permission_code'), 'admin_permission', ['code'], unique=True)
    # ### end Alembic commands ###
