"""add update_time

Revision ID: b2f14b3e3fb3
Revises: 62d0536a555e
Create Date: 2026-07-31 01:21:57.975813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f14b3e3fb3'
down_revision: Union[str, Sequence[str], None] = '62d0536a555e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('update_time', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('update_time', sa.Integer(), nullable=True))
    op.add_column('drift', sa.Column('update_time', sa.Integer(), nullable=True))
    op.add_column('gift', sa.Column('update_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.Integer(), nullable=True))
    op.add_column('wish', sa.Column('update_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'update_time')
    op.drop_column('user', 'update_time')
    op.drop_column('gift', 'update_time')
    op.drop_column('drift', 'update_time')
    op.drop_column('book', 'update_time')
    op.drop_column('admin_user', 'update_time')
    # ### end Alembic commands ###
