"""add_admin_operation_log

Revision ID: 1eae5d19c524
Revises: ee3aad681a1d
Create Date: 2026-08-05 21:43:59.111170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eae5d19c524'
down_revision: Union[str, Sequence[str], None] = 'ee3aad681a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('operator_role', sa.String(length=32), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('before_summary', sa.Text(), nullable=True),
    sa.Column('after_summary', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_operation_log_action'), 'admin_operation_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_create_time'), 'admin_operation_log', ['create_time'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_module'), 'admin_operation_log', ['module'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_operator_id'), 'admin_operation_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_operator_role'), 'admin_operation_log', ['operator_role'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_resource_id'), 'admin_operation_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_admin_operation_log_success'), 'admin_operation_log', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_operation_log_success'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_resource_id'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_operator_role'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_operator_id'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_module'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_create_time'), table_name='admin_operation_log')
    op.drop_index(op.f('ix_admin_operation_log_action'), table_name='admin_operation_log')
    op.drop_table('admin_operation_log')
    # ### end Alembic commands ###
