"""add_admin_role_menu_api

Revision ID: 0ba098c09c8c
Revises: a0ed83b620ad
Create Date: 2026-08-03 15:56:19.850451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba098c09c8c'
down_revision: Union[str, Sequence[str], None] = 'a0ed83b620ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role_menu_api',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_api_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_api_id'], ['admin_menu_api.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_api_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_menu_api')
    # ### end Alembic commands ###
